### ISSUE TITLE
Allow maps packed in archives to be imaged

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OP2MapImager#21]
I was playing around with this today on Linux. I noticed the MapImager will automatically unpack the tilesets from the VOLs, for use with FreeImage. It will not however unpack the maps themselves, and fails if the maps are not unpacked:
> Could not open file: Ashes.map

Related: Issue #16.

**Comment by Brett208** [comment]
Thanks for taking another look at this bug. I just reproduced it on Windows and figured out the problem. After opening a stream to the map in the archive, the map imager would attempt to create the map by referencing the filename, not the stream. Of course the filename doesn't exist if the map is only contained in the archive.

Please test the branch and make sure it actually fixed the issue you saw!

I'd still like to make it where wells are not unpacked when referenced for rendering. Maybe I will take a look at that before releasing.

-Brett

**Comment by DanRStevens** [comment]
I verified the patch fixes part of the problem. Namely, VOL files in the current directory, but no unpacked map files will now work.

I still get failures if the vol file is in a different directory. I notice the game will load vols from the same path as a specific map file, but still tries to look inside the vol files using the full path of the map, rather than just the filename. As the full path doesn't match the name in the VOL file, this causes the file to not be found.

```
~/code/opu/OP2MapImager$ ./OP2MapImager ../opu-git-svn/GameDownload/Outpost2/trunk/cm03.map
Render initialized (May take up to 45 seconds): cm03.map
Unable to locate ../opu-git-svn/GameDownload/Outpost2/trunk/cm03.map within directory or within an archive (vol or clm) in the directory.
```

A possible fix, within main.cpp, in the function ImageMapFromConsole:
```
auto mapBasename = XFile::GetFilename(mapFilename);
...
mapImager.ImageMap(renderFilename, mapBasename, renderSettings);
```

I suspect that map have implications when trying to reference unpacked map files though, so the patch idea may need a bit of work.

**Comment by DanRStevens** [comment]
My understanding was there was no caching.

I would like to see tileset caching when imaging a full directory. It may be simpler to leave caching enabled for all rendering, with single map renderings simply not benefiting from the caching.

I'm not sure I entirely understand the comment about recreating the resource manager for each individual map. This sounds inefficient. Do you mean if there are two game installs, and two maps are specified, each from a different install, then the VOL files corresponding to each install should be used? If so, that makes sense, and is quite some detailed thinking. I'm uncertain what is the proper way to go here.

A thought I sometimes have, is what if we allowed maps to be stored in a directory tree, much like other games allow. Then there would be different paths, but the same install, and hence the same tilesets. Maybe what we want is to separate the path from the map name arguments. Have a path to the Outpost 2 install (optional?), and a list of map names to image. The map names would be relative to the Outpost 2 install.

Come to think of it, it's a bit odd that you specify a full file path to a map that doesn't actually exist in the filesystem, but rather is packed inside some arbitrary VOL file within the directory given by the path part of the argument:
"path/to/file.map" => reads "file.map" from within "path/to/maps.vol"

Maybe the arguments should be:
"path/to/Outpost2/" "file.map"

**Comment by Brett208** [comment]
Dan,

I should be a bit more specific.

Currently, whenever you use OP2MapImager, the directory pointed to for the first map is setup with the ResourceManager. So archives outside of this directory are not considered when finding tilesets or maps. If you ask OP2MapImager to image maps from 2 different directories, it will not look for tilesets in the 2nd directory. To enable looking for files in the second directory, we could recreate the ResourceManager when the second directory is searched. To complicate things, if the tilesets are incorporated in an archive, they are unpacked into the directory you are currently working in even if the archive exists in a different location.

Could you make sure that you have pulled the most recent version of OP2Utility for use as a submodule when building OP2MapImager? Here is the behaviour I see:

 - Image loose map in current directory - success
 - Image archived map in current directory - success
 - Image loose map in relative directory - success
 - Image archived map in relative directory - failure
 - Image loose or archived map from an absolute directory - failure

After looking this over some more, I think the failures are occurring due to bugs in XFile and or the Resource Manager. I think the code in OP2MapImager itself is reasonable.

Do we want to keep XFile around, or would we rather just use the experimental filesystem library code in Resource Manager directly?

I think finding files is currently buggy using ResourceManager/XFile. I also think how the tilesets are found and accessed is vaguely defined.

XFile may need to be overhauled to get better results. Maybe unit tested as well. Not sure I want to tackle these right now.

-Brett

**Comment by DanRStevens** [comment]
Yes, I checked git status before building, and have just double checked it was built with the correct version of the submodule. The failure I'm reporting is the 3rd one you listed: "Image archived map in relative directory - failure"

I believe this is a bug in MapImager itself, and not OP2Utility. I believe this because an edit to MapImager allows this to work. It's a path issue in that the full path string is searched in the VOL file, rather than just the filename.

This edit `ImageMapFromConsole` in `Main.cpp` allows the 3rd case to work:
```cpp
auto mapBasename = XFile::GetFilename(mapFilename);
...
mapImager.ImageMap(renderFilename, mapBasename, renderSettings);
```

If I run: `./OP2MapImager ../opu-git-svn/GameDownload/Outpost2/trunk/cm03.map`
It loads archives from path: "../opu-git-svn/GameDownload/Outpost2/trunk/"
It then searches within the archives for: "../opu-git-svn/GameDownload/Outpost2/trunk/cm03.map"
With the edit, it instead searches within the archives for: "cm03.map"

----

I'm not looking to make changes to XFile at this time.

**Comment by DanRStevens** [comment]
I've just confirmed the 5th listed case does not work: "Image loose or archived map from an absolute directory - failure"

I was not aware of that failure.

The error message seems to suggest it is stripping the leading "/" from the path.

**Comment by Brett208** [comment]
I'm going to mark this as resolved. I've ran through a fair number of tests and things seems to be working well now (minus the ResourceManager issue documented in OP2Utility).
