### ISSUE TITLE
Remove bitmap files from project history

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OP2MapImager#47]
Seems the bitmap files exist within project history. They should probably be removed. I also saw a few other files in there too that should probably be gone.

Paths:
```
OP2MapImager/well00??.bmp
OP2MapImager/TestFiles/maps01.vol
OP2MapImager/TestFiles/maps02.vol
OP2MapImager/TestFiles/SGAME0.OP2
```

I haven't check if they are dummy files or not.

This may require a force push of master to fix. Care will need to be taken to ensure we don't accidentally remove project history that we want to keep.

**Comment by Brett208** [comment]
@DanRStevens,

There does not appear to be a TestFiles directory or well files themselves in the current master branch of the repository (I'm looking on GitHub). There is only one branch in the public repository (master). 

Are you detecting them at a previous commit or something? If I had accidentally added them and noticed, I'm certain I would have consulted you on how to delete them from history instead of just deleting them with a commit as we had discussed this in the past. Unless they exist in history from before being pushed to GitHub but I think you took care of that when porting over.

I do often put Test or TestFiles directory in place locally for testing. Also, the older version of the map imager would have automatically pulled the wells from their archive in the root directory.

-Brett

**Comment by DanRStevens** [comment]
Hmm, my mistake. Seems they only existed in my local clone. I just did a fresh clone from GitHub and none of those files are present.

It's quite possible I ran a `git stash` at some point when those files were present (and not ignored), which would have copied the objects into the repository (though not on master). I saw them when I did an object dump of the entire repository and sorted by size. I never checked when, why, or how they were added as objects.

I'm going to close this as not actually an issue.
